### ISSUE TITLE
question: go-word2vec for building a classifier

### ISSUE THREAD

**Issue by Arnold1** [shirayu/go-word2vec#1]
Hi,

would it be possible to implement a sentiment classifier using word2vec for classifying a sentences in 3 categories (pos/neg/neutral)?
all i need is a text corpus and go-word2vec would transform my sentence and give me a feature vector to be used to train the classifier? could you describe how that works?

Thanks,

**Comment by shirayu** [comment]
Though I consider that vectors of word2vec are not necessarily required though they can be features for the sentiment classification.
So, the question is out of my support.
Sorry.
