### ISSUE TITLE
Lost first character from each word when loading model

### ISSUE THREAD

**Issue by kangaechu** [shirayu/go-word2vec#2]
Hi.

When loading the model using the NewModel method, the first letter of each word is missing.

```python
import (
  "fmt"
  "log"
  "os"

  "github.com/shirayu/go-word2vec"
)

func main() {
  f, err := os.Open("model/GoogleNews-vectors-negative300.bin")
  if err != nil {
    log.Fatal("open error", err)
  }
  model, err := word2vec.NewModel(f)
  if err != nil {
    log.Fatal("model read error", err)
  }
  vocab := model.GetVocab()
  fmt.Println(vocab["raditional_Knowledge"])
}
```
I use Google News pre-trained model.
https://code.google.com/archive/p/word2vec/

Original word is "Traditional_Knowledge", but it matches "raditional_Knowledge".

Do you have any reason to start reading from second character?

**Comment by shirayu** [comment]
Thank you for your report!
It is a bug.
I fixed it.
